/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Bitacora { 
    carreraNombre?: string;
    cedula?: string;
    descripcionBitacora?: string;
    fechaBitacora?: string;
    id?: number;
    idLaboratorio?: number;
    nivelNombre?: string;
    nombreAsignatura?: string;
    nombreEquipo?: string;
}